//
//  WikiSearchPresenter.swift
//  Monetap
//
//  Created by Garry Patel on 06/09/18.
//  Copyright (c) 2018 com.ways. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WikiSearchPresentationLogic
{
  func presentSomething(response: WikiSearch.SearchWiki.Response)
}

class WikiSearchPresenter: WikiSearchPresentationLogic
{
  weak var viewController: WikiSearchDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: WikiSearch.SearchWiki.Response)
  {
    let viewModel = WikiSearch.SearchWiki.ViewModel(batchcomplete: response.batchcomplete, continues: response.continues, query: response.query, isError: response.isError, message: response.message)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
