//
//  WikiSearchInteractor.swift
//  Monetap
//
//  Created by Garry Patel on 06/09/18.
//  Copyright (c) 2018 com.ways. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WikiSearchBusinessLogic
{
  func doSomething(request: WikiSearch.SearchWiki.Request)
}

protocol WikiSearchDataStore
{
  //var name: String { get set }
}

class WikiSearchInteractor: WikiSearchBusinessLogic, WikiSearchDataStore
{
  var presenter: WikiSearchPresentationLogic?
  var worker: WikiSearchWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: WikiSearch.SearchWiki.Request)
  {
    worker = WikiSearchWorker()
    worker?.getSearchFromServer(request, { (query, batchComplete, continues, isError, message) in
        
        let response = WikiSearch.SearchWiki.Response(batchcomplete: batchComplete, continues: continues, query: query, isError: isError, message: message)
        self.presenter?.presentSomething(response: response)
    })
    
    
  }
}
