//
//  WikiSearchModels.swift
//  Monetap
//
//  Created by Garry Patel on 06/09/18.
//  Copyright (c) 2018 com.ways. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum WikiSearch
{
  // MARK: Use cases
  
  enum SearchWiki
  {
    struct Request
    {
        var searchStr: String?
        var limit : Int?
    }
    
    struct Response
    {
        var  batchcomplete : Bool?
        var continues: Continue?
        var query : Query?
        var isError: Bool?
        var message: String?
    }
    
    struct ViewModel
    {
        var  batchcomplete : Bool?
        var continues: Continue?
        var query : Query?
        var isError: Bool?
        var message: String?
    }
  }
}
